<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml">
			<head>
				<title>XML Sitemap - Abdelouahab Bella Portfolio</title>
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				<style type="text/css">
					body {
						font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
						color: #333;
						background: #f1f1f1;
						font-size: 14px;
						line-height: 1.5;
					}
					
					#sitemap {
						max-width: 980px;
						margin: 0 auto;
						background: #fff;
						padding: 20px;
						box-shadow: 0 1px 3px rgba(0,0,0,.1);
					}
					
					#sitemap .header {
						border-bottom: 1px solid #eee;
						padding-bottom: 10px;
						margin-bottom: 20px;
					}
					
					#sitemap .header h1 {
						font-size: 24px;
						font-weight: normal;
						margin: 0;
					}
					
					table {
						width: 100%;
						border-collapse: collapse;
					}
					
					th {
						text-align: left;
						border-bottom: 1px solid #ddd;
						padding: 8px;
						background: #f5f5f5;
					}
					
					td {
						padding: 8px;
						border-bottom: 1px solid #eee;
					}
					
					tr:nth-child(even) {
						background: #f9f9f9;
					}
					
					.url-cell {
						width: 60%;
					}
					
					.loc a:link, .loc a:visited {
						color: #0073aa;
						text-decoration: none;
					}
					
					.loc a:hover {
						color: #00a0d2;
						text-decoration: underline;
					}
					
					.priority-0\.8 {
						background: #efe;
					}
					
					.priority-0\.9 {
						background: #dfd;
					}
					
					.priority-1\.0 {
						background: #cfc;
					}
					
					footer {
						max-width: 980px;
						margin: 10px auto;
						font-size: 12px;
						color: #999;
						text-align: center;
					}
				</style>
			</head>
			<body>
				<div id="sitemap">
					<div class="header">
						<h1>XML Sitemap - Abdelouahab Bella Portfolio</h1>
						<p>This is an XML Sitemap, meant for consumption by search engines to improve SEO.</p>
					</div>
					<div id="content">
						<table>
							<tr>
								<th class="url-cell">URL</th>
								<th>Priority</th>
								<th>Change Frequency</th>
							</tr>
							<xsl:for-each select="sitemap:urlset/sitemap:url">
								<tr class="priority-{sitemap:priority}">
									<td class="loc">
										<a href="{sitemap:loc}">
											<xsl:value-of select="sitemap:loc"/>
										</a>
									</td>
									<td>
										<xsl:value-of select="sitemap:priority"/>
									</td>
									<td>
										<xsl:value-of select="sitemap:changefreq"/>
									</td>
								</tr>
							</xsl:for-each>
						</table>
					</div>
				</div>
				<footer>
					Generated by Abdelouahab Bella's Portfolio | <a href="https://bellaabdelouahab.github.io/#/site-map">View Site Map</a>
				</footer>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
